return {
    filetypes = {
      'c',
      'cmake',
      'cpp',
      'cs',
      'dart',
      'gitcommit',
      'go',
      'haskell',
      'html',
      'java',
      'javascript',
      'lua',
      'markdown',
      'nix',
      'php',
      'python',
      'ruby',
      'rust',
      'swift',
      'toml',
      'text',
      'typescript',
      'typescriptreact',
      'typst',
    },
    settings = {
        ['harper-ls'] = {
            linters = {
                PossessiveYour = true,
                FastPaste = true,
                Somehow = true,
                Anyhow = true,
                LetsConfusion = true,
                TurnItOff = true,
                SpellCheck = true,
                ChangeTack = true,
                MyHouse = true,
                Malaysia = true,
                BeenThere = true,
                BatedBreath = true,
                ThatThis = true,
                Notwithstanding = true,
                UseGenitive = false,
                OperativeSystem = true,
                Likewise = true,
                ItCan = true,
                Somebody = true,
                Upset = true,
                NationalCapitals = true,
                OutOfDate = true,
                PiqueInterest = true,
                BaitedBreath = true,
                DespiteOf = true,
                Overnight = true,
                Intact = true,
                Nonetheless = true,
                Whereupon = true,
                SoonerOrLater = true,
                AvoidCurses = true,
                SupposedTo = true,
                AmazonNames = true,
                Whereas = true,
                RoadMap = true,
                Instead = true,
                OxfordComma = true,
                Somewhere = true,
                ThatChallenged = true,
                SentenceCapitalization = true,
                ChockFull = true,
                WasAloud = true,
                Underclock = true,
                Canada = true,
                SomewhatSomething = true,
                ModalOf = true,
                HadOf = true,
                PluralConjugate = false,
                Upward = true,
                Anybody = true,
                SameAs = true,
                MutePoint = true,
                PocketCastsNames = true,
                Forthwith = true,
                BareInMind = true,
                NeedHelp = true,
                Multimedia = true,
                Holidays = true,
                Backplane = true,
                WrongQuotes = false,
                NoOxfordComma = false,
                Misuse = true,
                Multicore = true,
                CorrectNumberSuffix = true,
                WantBe = true,
                KindRegards = true,
                Therefore = true,
                RepeatedWords = true,
                FaceFirst = true,
                MetaNames = true,
                EnMasse = true,
                MergeWords = true,
                GoingTo = true,
                OfCourse = true,
                JetpackNames = true,
                AppleNames = true,
                MultipleSequentialPronouns = true,
                Nothing = true,
                ThoughtProcess = true,
                However = true,
                HungerPang = true,
                Overclocking = true,
                LeftRightHand = true,
                CondenseAllThe = true,
                ThenThan = true,
                HyphenateNumberDay = true,
                SneakingSuspicion = true,
                AzureNames = true,
                Devops = true,
                ChineseCommunistParty = true,
                CapitalizePersonalPronouns = true,
                SpelledNumbers = false,
                GoogleNames = true,
                FatalOutcome = true,
                WillContain = true,
                Widespread = true,
                IAm = true,
                BackInTheDay = true,
                SpecialAttention = true,
                LetAlone = true,
                Overload = true,
                AndIn = true,
                AnA = true,
                UnclosedQuotes = true,
                ThatWhich = true,
                EludedTo = true,
                Worldwide = true,
                MicrosoftNames = true,
                DayOneNames = true,
                Misused = true,
                BoringWords = false,
                DotInitialisms = true,
                Regardless = true,
                Nobody = true,
                Itself = true,
                BadRap = true,
                ByAccident = true,
                WaveFunction = true,
                Desktop = true,
                Everywhere = true,
                Matcher = true,
                OperativeSystems = true,
                LinkingVerbs = false,
                Americas = true,
                Australia = true,
                TerminatingConjunctions = true,
                Koreas = true,
                OceansAndSeas = true,
                Anywhere = true,
                Middleware = true,
                Hereby = true,
                Henceforth = true,
                HumanLife = true,
                HopHope = true,
                NumberSuffixCapitalization = true,
                EllipsisLength = true,
                Insofar = true,
                BeckAndCall = true,
                Laptop = true,
                LongSentences = true,
                CurrencyPlacement = true,
                AndTheLike = true,
                PointIsMoot = true,
                UnitedOrganizations = true,
                WordPressDotcom = true,
                Proofread = true,
                Misunderstood = true,
                BanTogether = true,
                AvoidAndAlso = true,
                Myself = true,
                StateOfTheArt = true,
                NotTo = true,
                Postpone = true,
                Into = true,
                InThe = true,
                Misunderstand = true,
                CompoundNouns = true,
                PronounContraction = true,
                Spaces = true,
                TumblrNames = true,
                IsKnownFor = true,
                Multithreading = true,
                Overall = true,
                Furthermore = true,
                ExpandTimeShorthands = true,
                CanBeSeen = true,
                Thereupon = true,
                Countries = true,
            },
            userDictPath = vim.fn.stdpath('data') .. "/dict.txt",
        },
    },
}

